package migration.mybatis.mapper.amigo_0149_c;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.transaction.annotation.Transactional;

import migration.mybatis.domain.amigo_0149_c.VBanktrade;

@Transactional(transactionManager = "amigoCManager")
public interface VBanktradeMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMIGO_0149_C.T_JUDGE_RESULT
     *
     * @mbg.generated Thu May 08 16:16:40 JST 2025
     */
    long countByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMIGO_0149_C.T_JUDGE_RESULT
     *
     * @mbg.generated Thu May 08 16:16:40 JST 2025
     */
    List<VBanktrade> selectByExample(@Param("start") int start, @Param("end") int end);

}
