package migration.mybatis.mapper.amigo_0149_c;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.transaction.annotation.Transactional;

import migration.mybatis.domain.amigo_0149_c.ParentKey;
import migration.mybatis.domain.amigo_0149_c.VJudgeMain;

@Transactional(transactionManager = "amigoCManager")
public interface VJudgeMainMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMIGO_0149_C.T_JUDGE_MAIN
     *
     * @mbg.generated Thu May 08 16:16:40 JST 2025
     */
    long countByExample();

    /**
     *
     * @param ids
     * @return
     */
    List<VJudgeMain> selectByExample(@Param("start") int start, @Param("end") int end);

    /**
     *
     * @param offset
     * @param size
     * @return
     */
    List<ParentKey> selectPage(@Param("offset") int offset, @Param("size") int size);

    /**
     *
     * @param fromNo
     * @param toNo
     * @return
     */
    List<Long> selectMainIdsByRowWindow(@Param("fromNo") int fromNo, @Param("toNo") int toNo);

}
