package migration.mybatis.mapper.amigo_0149_c;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.transaction.annotation.Transactional;

import migration.mybatis.domain.amigo_0149_c.VSendfaxExt;

@Transactional(transactionManager = "amigoCManager")
public interface VSendfaxExtMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMIGO_0149_C.CT_SENDFAX
     * @mbg.generated  Thu May 08 17:08:33 JST 2025
     */
    List<VSendfaxExt> selectByExample(@Param("start") int start, @Param("end") int end);

}
