package migration.mybatis.mapper.amigo_0149_c;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import migration.mybatis.domain.amigo_0149_c.VWebdata;

public interface VWebdataMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMIGO_0149_C.T_JUDGE_RESULT
     *
     * @mbg.generated Thu May 08 16:16:40 JST 2025
     */
    List<VWebdata> selectByExample(@Param("start") int start, @Param("end") int end);

}
