package migration.mybatis.domain.amigo_0149_c;

import java.io.Serializable;

import lombok.Data;

@Data
public class ParentKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AMIGO_0149_C.T_JUDGE_MAIN.REQUEST_NO
     * @mbg.generated Tue Jul 08 20:52:02 JST 2025
     */
    private Long requestNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AMIGO_0149_C.T_JUDGE_MAIN.REQUEST_NO_TEMP
     * @mbg.generated Tue Jul 08 20:52:02 JST 2025
     */
    private Long requestNoTemp;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AMIGO_0149_C.T_JUDGE_MAIN.REQUEST_NO_PERF
     * @mbg.generated Tue Jul 08 20:52:02 JST 2025
     */
    private Long requestNoPerf;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AMIGO_0149_C.T_JUDGE_MAIN.RECEPTION_DATE
     * @mbg.generated Tue Jul 08 20:52:02 JST 2025
     */
    private Integer receptionDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AMIGO_0149_C.T_JUDGE_MAIN.RECEPTION_TIME
     * @mbg.generated Tue Jul 08 20:52:02 JST 2025
     */
    private Integer receptionTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AMIGO_0149_C.T_JUDGE_MAIN.RECEPTION_NO
     * @mbg.generated Tue Jul 08 20:52:02 JST 2025
     */
    private Integer receptionNo;
}
