package migration.mybatis.domain.amigo_0149_c;

import java.io.Serializable;
import java.nio.file.Path;
import java.util.List;

import lombok.Data;

@Data
public class VImgpr implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.REQUEST_NO
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Long requestNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.RECEPTION_DATE
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer receptionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.RECEPTION_NO
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer receptionNo;

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.PRIORITY_ID
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String priorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.ACQUIRE_ID
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String acquireId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.DEL_FLAG
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Short delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.CREATE_CD
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer createCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.CREATE_NAME
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.CREATE_DATE
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.CREATE_TIME
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.CREATE_PG
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String createPg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.UPDATE_CD
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer updateCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.UPDATE_NAME
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.UPDATE_DATE
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.UPDATE_TIME
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_IMGPR.UPDATE_PG
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String updatePg;

    /**
     *
     */
    private List<Path> imageList;

}
