package migration.mybatis.domain.amigo_0149_c;

import java.io.Serializable;

import lombok.Data;

@Data
public class VJudgeResult implements Serializable {

    // -- T_JUDGE_RESULT --
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.REQUEST_NO
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Long requestNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.HISTORY_NO
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Short historyNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.LAST_UP_CD
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Integer lastUpcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.LAST_UP_NAME
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private String lastUpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.LAST_UP_DATE
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Integer lastUpDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.LAST_UP_TIME
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Integer lastUpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.LAST_UP_COMMENT
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private String lastUpComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.LAST_UP_RES
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private String lastUpRes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.LAST_UP_RES_TXT
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private String lastUpResTxt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.STATUS
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.NEW_FLG
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private String newFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.CREATE_CD
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Integer createCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.CREATE_NAME
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.CREATE_DATE
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Integer createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.CREATE_TIME
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.CREATE_PG
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private String createPg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.UPDATE_CD
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Integer updateCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.UPDATE_NAME
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.UPDATE_DATE
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Integer updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Integer updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_RESULT.UPDATE_PG
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private String updatePg;

}
