package migration.mybatis.domain.amigo_0149_c;

import java.io.Serializable;

import lombok.Data;

@Data
public class VRequestNo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_MAIN.REQUEST_NO
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Long requestNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_MAIN.REQUEST_NO_TEMP
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Long requestNoTemp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_JUDGE_MAIN.REQUEST_NO_PERF
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private Long requestNoPerf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.T_ENTRY_MAIN.REQUEST_ID
     *
     * @mbg.generated Thu Jun 19 13:18:39 JST 2025
     */
    private String requestId;

}
