package migration.mybatis.domain.amigo_0149_c;

import java.io.Serializable;
import java.nio.file.Path;
import java.util.List;

import lombok.Data;

@Data
public class VSendfaxExt implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.REQUEST_NO
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Long requestNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.REQUEST_DATE
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer requestDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.REQUEST_TIME
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.REQUEST_CHARGE_CD
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer requestChargeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.REQUEST_ID
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.GUARANTY_CD
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Short guarantyCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.GUARANTY_NAME
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String guarantyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.GUARANTY_POST
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String guarantyPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.FAX_NO_1
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String faxNo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.FAX_NO_2
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String faxNo2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.FAX_NO_3
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String faxNo3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.GOODS_CD
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer goodsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.SEND_FILE_NAME
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String sendFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.SEND_NO
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String sendNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.CONF_DATE
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer confDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.CONF_TIME
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer confTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.CONF_CHARGE_CD
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer confChargeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.CONF_ID
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String confId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.CONF_COMMENT
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String confComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.APP_DATE
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer appDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.APP_TIME
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer appTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.APP_CHARGE_CD
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer appChargeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.APP_ID
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.APP_COMMENT
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String appComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.SEND_DATE
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer sendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.SEND_TIME
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private Integer sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMIGO_0149_C.CT_SENDFAX_EXT.SEND_ID
     *
     * @mbg.generated Fri May 09 11:39:25 JST 2025
     */
    private String sendId;

    /**
     *
     */
    private List<Path> imageList;

}
