spring:
  application:
    name: migration_batch_jutaku
  http:
    encoding:
      charset: Shift_JIS
      enabled: true
      force: true
  datasource:
    source:
      url: jdbc:oracle:thin:@E00736SV0001:1521:ORCL
      username: SZB_SMS
      password: SZB_SMS
      driver-class-name: oracle.jdbc.OracleDriver
    target:
      url: jdbc:oracle:thin:@E00736SV0001:1521:ORCL
      username: ITF_SMS
      password: SCP00ITF_SMS
      driver-class-name: oracle.jdbc.OracleDriver
  batch:
    job:
      enabled: false

mybatis:
  mapper-locations: classpath*:migration/mybatis/mapper/**/*.xml
  type-aliases-package: migration.domain

logging:
  level:
    migration: INFO
    org.springframework.batch: INFO

migration:
  management:
    batch-size: 100
    max-iterations: 3
  range:
    batch-size: 100
    test-limit: 1000
